spring.application.name=twitter-clone

# Database
spring.datasource.url=jdbc:postgresql://dpg-d6k315q4d50c73d834fg-a:5432/kursat
spring.datasource.username=kursatakpnr
spring.datasource.password=rqiCSdlfqL0yGYkZ39M10EXF1jU9AZ0P
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS
app.cors.allowed-origins=https://twitter-frontend-lovat.vercel.app,http://localhost:3000

# JWT
app.jwt.secret=twitterCloneJwtSecretKeyAtLeastThirtyTwoCharactersLong2026
app.jwt.expiration-ms=86400000