spring.application.name=twitter-clone

spring.datasource.url=jdbc:postgresql://localhost:5432/twitter_clone
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=twitterCloneJwtSecretKeyAtLeastThirtyTwoCharactersLong2026
app.jwt.expiration-ms=86400000
